# Generated by Django 2.2.12 on 2020-04-24 08:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0003_auto_20200424_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatroom.Room'),
        ),
        migrations.AlterField(
            model_name='message',
            name='stamp',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
